# Calvin's bashrc (mostly from the autogenerated Cygwin bashrc)

# If not running interactively, don't do anything
[[ "$-" != *i* ]] && return


### ALIASES ###

# Epic colors
alias grep='grep --color'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias ls='ls --color=auto'

# Get last command status
status()
{
	s=$?
	if [ $s -eq 0 ]
	then
		echo -en "\e[32m✔  "
	else
		echo -en "\e[31m✖  "
	fi
	echo -e "$s\e[0m"
}

alias please="sudo"
alias paste-path="cd \"$(head -1 /tmp/path)\""
#alias figlet="figlet -d ~/figlet-fonts/"


### PATH ###
export PATH=$PATH:"/home/$USER/bin/"



### PROMPT ###
# Looks like:
# ✔  0 - user@hostname ~/path
# $ command 

# Status ex. command not found:
# ✖  127 - user@hostname ~/path
# $ 

export PS1="\[\e[0m\]\[\e]0;\w\a\]\n\$(status) - \[\e[32m\]\u@\h \[\e[33m\]\w\[\e[94m\]\n\$\[\e[0m\] "


### NODE VERSION MANAGER ###
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion